spring:
  profiles:
    active: dev
  application:
    name: gateway-server
  config:
    import: optional:configserver:http://${SECURITY_USERNAME}:${SECURITY_PASSWORD}@localhost:${CONFIG_SERVER_PORT}

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${SECURITY_USERNAME}:${SECURITY_PASSWORD}@localhost:${EUREKA_SERVER_PORT}/eureka/

user-details:
  username: ${SECURITY_USERNAME}
  password: ${SECURITY_PASSWORD}
  role: ${SECURITY_ROLE}