spring:
  profiles:
    active: dev
  application:
    name: udtk-switch
  config:
    import: optional:configserver:http://${SECURITY_USERNAME}:${SECURITY_PASSWORD}@localhost:${CONFIG_SERVER_PORT}

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${SECURITY_USERNAME}:${SECURITY_PASSWORD}@localhost:${EUREKA_SERVER_PORT}/eureka/
