server:
  port: ${EUREKA_SERVER_PORT}

user-details:
  username: ${USERNAME}
  password: ${PASSWORD}
  role: ${ROLE}

spring:
  profiles:
    active: dev
    include: local
  application:
    name: udtk-eureka
  security:
    user:
      name: ${USERNAME}
      password: ${PASSWORD}

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${USERNAME}:${PASSWORD}@localhost:${EUREKA_SERVER_PORT}/eureka/
