server:
  port: ${EUREKA_SERVER_PORT}

user-details:
  username: ${EUREKA_SERVER_USERNAME}
  password: ${EUREKA_SERVER_PASSWORD}
  role: ${EUREKA_SERVER_ROLE}

spring:
  profiles:
    active: dev
    include: local
  application:
    name: udtk-eureka

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false