server:
  port: ${EUREKA_SERVER_PORT}

user-details:
  username: ${SECURITY_USERNAME}
  password: ${SECURITY_PASSWORD}
  role: ${SECURITY_ROLE}

spring:
  profiles:
    active: dev
    include: local
  application:
    name: udtk-eureka
  security:
    user:
      name: ${SECURITY_USERNAME}
      password: ${SECURITY_PASSWORD}

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${EUREKA_SERVER_USERNAME}:${EUREKA_SERVER_PASSWORD}@localhost:${EUREKA_SERVER_PORT}/eureka/
