user-details:
  username: ${CONFIG_SERVER_USER_NAME}
  password: ${CONFIG_SERVER_PASSWORD}
  role: ${CONFIG_SERVER_USER_ROLE}

spring:
  profiles:
    active: dev
    include: local
  application:
    name: udtk-core
  config:
    import: optional:configserver:http://${CONFIG_SERVER_USER_NAME}:${CONFIG_SERVER_PASSWORD}@localhost:${CONFIG_SERVER_PORT}

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${EUREKA_SERVER_USER_NAME}:${EUREKA_SERVER_PASSWORD}@localhost:${EUREKA_SERVER_PORT}/eureka/
