server:
  port: 9000

user-details:
  username: ${USER_NAME}
  password: ${PASSWORD}
  role: ${ROLE}

spring:
  profiles:
    active: dev
    include: local
  application:
    name: udtk-config

  cloud:
    config:
      server:
        git:
          uri: ${CONFIG_URI}
          username: ${CONFIG_USERNAME}
          password: ${CONFIG_PASSWORD}
          ignore-local-ssh-settings: true
          private-key: ${CONFIG_PRIVATE_KEY}